// log in as Troels
POST https://localhost:7130/auth/login
Content-Type: application/json

{ "Username" : "trmo", "Password" : "onetwo3FOUR" }

### // log in as Jakob
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{  "username" : "1234",
  "password":"123" }

### // allow anonymous
GET https://localhost:7130/test/allowanon

### // must be authorized
GET https://localhost:7130/test/authorized
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI0M2QxN2UwMi04Mjg4LTQ3YTYtYjNlZi1hMmRkNjJjZjM4ZjkiLCJpYXQiOiIwMi4xMi4yMDIyIDEwOjQ2OjM0IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRybW8iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUZWFjaGVyIiwiRGlzcGxheU5hbWUiOiJUcm9lbHMgTW9ydGVuc2VuIiwiRW1haWwiOiJ0cm1vQHZpYS5kayIsIkFnZSI6IjM2IiwiRG9tYWluIjoidmlhIiwiU2VjdXJpdHlMZXZlbCI6IjQiLCJleHAiOjE2Njk5ODE1OTQsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.r2A9nnGGMDaPeVZEJryo_LGzo65mmH7r-p538MH47sk

###     // policy mustbevia allowed
GET https://localhost:7130/test/mustbevia
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiIyMzYwYWZjNC01ZDQ4LTRlNTctOGYxZC0wYmZlZTFkOWM3ZjIiLCJpYXQiOiIwNi8xMC8yMDIyIDExOjE1OjQxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImprbnIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiRGlzcGxheU5hbWUiOiJKYWtvYiBSYXNtdXNzZW4iLCJFbWFpbCI6Impha29iQGdtYWlsLmNvbSIsIkFnZSI6IjM0IiwiRG9tYWluIjoidmlhIiwiU2VjdXJpdHlMZXZlbCI6IjIiLCJleHAiOjE2NjUwNTg1NDEsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.R1pVBYWQyX_u6W6jJKf2fyVHJvtum3CDgQP3X3otDEI7fQNKZ2yMMA1Pq2Pe5WujGuO0R8nNuqSnVrmL7r8Thg

###    // manual checking MustBeTeacher
GET https://localhost:7130/test/manualcheck
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJkY2JlNTU4Yi1hZjBlLTRmNWUtYWIyNC0wNjBiYzUyZWUxNTkiLCJpYXQiOiIwNy8wOC8yMDIyIDA5OjQ1OjQ4IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImprbnIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiRGlzcGxheU5hbWUiOiJKYWtvYiBSYXNtdXNzZW4iLCJFbWFpbCI6Impha29iQGdtYWlsLmNvbSIsIkFnZSI6IjM0IiwiRG9tYWluIjoiZ21haWwiLCJleHAiOjE2NTk4NjkxNDgsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.3CmYYv_IN9VKHJCLVhyU_y-NNuXO38_TfIoypLdLTTa9QAEbSLdO9h9e2RHIvEIcqJBXScKTLBxwPhihj0obwA





