// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package via.generatedprotos;

public interface AdviceCreationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:generatedprotos.AdviceCreation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>int32 adviceId = 2;</code>
   * @return The adviceId.
   */
  int getAdviceId();
}
