// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package via.generatedprotos;

public final class Definitions {
  private Definitions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generatedprotos_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generatedprotos_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generatedprotos_ListUsers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generatedprotos_ListUsers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generatedprotos_WaterUsage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generatedprotos_WaterUsage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generatedprotos_ElectricityUsage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generatedprotos_ElectricityUsage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generatedprotos_WaterUsageAdvice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generatedprotos_WaterUsageAdvice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generatedprotos_ElectricityUsageAdvice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generatedprotos_ElectricityUsageAdvice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generatedprotos_ID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generatedprotos_ID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generatedprotos_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generatedprotos_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generatedprotos_ListWaterUsage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generatedprotos_ListWaterUsage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generatedprotos_ListElectricityUsage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generatedprotos_ListElectricityUsage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generatedprotos_ListWaterUsageAdvice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generatedprotos_ListWaterUsageAdvice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generatedprotos_ListElectricityUsageAdvice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generatedprotos_ListElectricityUsageAdvice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generatedprotos_AdviceCreation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generatedprotos_AdviceCreation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021definitions.proto\022\017generatedprotos\"R\n\004" +
      "User\022\n\n\002id\030\001 \001(\005\022\020\n\010username\030\002 \001(\t\022\020\n\010pa" +
      "ssword\030\003 \001(\t\022\014\n\004role\030\004 \001(\005\022\014\n\004area\030\005 \001(\005" +
      "\"1\n\tListUsers\022$\n\005users\030\001 \003(\0132\025.generated" +
      "protos.User\"U\n\nWaterUsage\022\n\n\002id\030\001 \001(\005\022\016\n" +
      "\006amount\030\002 \001(\001\022\r\n\005month\030\003 \001(\005\022\014\n\004year\030\004 \001" +
      "(\005\022\016\n\006userId\030\005 \001(\005\"[\n\020ElectricityUsage\022\n" +
      "\n\002id\030\001 \001(\005\022\016\n\006amount\030\002 \001(\001\022\r\n\005month\030\003 \001(" +
      "\005\022\014\n\004year\030\004 \001(\005\022\016\n\006userId\030\005 \001(\005\",\n\020Water" +
      "UsageAdvice\022\n\n\002id\030\001 \001(\005\022\014\n\004body\030\002 \001(\t\"2\n" +
      "\026ElectricityUsageAdvice\022\n\n\002id\030\001 \001(\005\022\014\n\004b" +
      "ody\030\002 \001(\t\"\020\n\002ID\022\n\n\002id\030\001 \001(\005\"\007\n\005Empty\"<\n\016" +
      "ListWaterUsage\022*\n\005water\030\001 \003(\0132\033.generate" +
      "dprotos.WaterUsage\"N\n\024ListElectricityUsa" +
      "ge\0226\n\013electricity\030\001 \003(\0132!.generatedproto" +
      "s.ElectricityUsage\"H\n\024ListWaterUsageAdvi" +
      "ce\0220\n\005water\030\001 \003(\0132!.generatedprotos.Wate" +
      "rUsageAdvice\"Z\n\032ListElectricityUsageAdvi" +
      "ce\022<\n\013electricity\030\001 \003(\0132\'.generatedproto" +
      "s.ElectricityUsageAdvice\"2\n\016AdviceCreati" +
      "on\022\016\n\006userId\030\001 \001(\005\022\020\n\010adviceId\030\002 \001(\0052\332\007\n" +
      "\024ResourcesConsumption\022[\n\023LogElectricityU" +
      "sage\022!.generatedprotos.ElectricityUsage\032" +
      "!.generatedprotos.ElectricityUsage\022I\n\rLo" +
      "gWaterUsage\022\033.generatedprotos.WaterUsage" +
      "\032\033.generatedprotos.WaterUsage\022I\n\016GetWate" +
      "rUsages\022\026.generatedprotos.Empty\032\037.genera" +
      "tedprotos.ListWaterUsage\022U\n\024GetElectrici" +
      "tyUsages\022\026.generatedprotos.Empty\032%.gener" +
      "atedprotos.ListElectricityUsage\022L\n\020Updat" +
      "eWaterUsage\022\033.generatedprotos.WaterUsage" +
      "\032\033.generatedprotos.WaterUsage\022^\n\026UpdateE" +
      "lectricityUsage\022!.generatedprotos.Electr" +
      "icityUsage\032!.generatedprotos.Electricity" +
      "Usage\022?\n\020DeleteWaterUsage\022\023.generatedpro" +
      "tos.ID\032\026.generatedprotos.Empty\022E\n\026Delete" +
      "ElectricityUsage\022\023.generatedprotos.ID\032\026." +
      "generatedprotos.Empty\022E\n\021GetWaterUsageBy" +
      "Id\022\023.generatedprotos.ID\032\033.generatedproto" +
      "s.WaterUsage\022Q\n\027GetElectricityUsageById\022" +
      "\023.generatedprotos.ID\032!.generatedprotos.E" +
      "lectricityUsage\022M\n\025GetWaterUsageByUserId" +
      "\022\023.generatedprotos.ID\032\037.generatedprotos." +
      "ListWaterUsage\022Y\n\033GetElectricityUsageByU" +
      "serId\022\023.generatedprotos.ID\032%.generatedpr" +
      "otos.ListElectricityUsage2\276\002\n\016UserManage" +
      "ment\022:\n\nCreateUser\022\025.generatedprotos.Use" +
      "r\032\025.generatedprotos.User\022>\n\010GetUsers\022\026.g" +
      "eneratedprotos.Empty\032\032.generatedprotos.L" +
      "istUsers\0229\n\013GetUserById\022\023.generatedproto" +
      "s.ID\032\025.generatedprotos.User\022:\n\nUpdateUse" +
      "r\022\025.generatedprotos.User\032\025.generatedprot" +
      "os.User\0229\n\nDeleteUser\022\023.generatedprotos." +
      "ID\032\026.generatedprotos.Empty2\314\n\n\020AdviceMan" +
      "agement\022^\n\026CreateWaterUsageAdvice\022!.gene" +
      "ratedprotos.WaterUsageAdvice\032!.generated" +
      "protos.WaterUsageAdvice\022p\n\034CreateElectri" +
      "cityUsageAdvice\022\'.generatedprotos.Electr" +
      "icityUsageAdvice\032\'.generatedprotos.Elect" +
      "ricityUsageAdvice\022U\n\024GetWaterUsageAdvice" +
      "s\022\026.generatedprotos.Empty\032%.generatedpro" +
      "tos.ListWaterUsageAdvice\022a\n\032GetElectrici" +
      "tyUsageAdvices\022\026.generatedprotos.Empty\032+" +
      ".generatedprotos.ListElectricityUsageAdv" +
      "ice\022^\n\026UpdateWaterUsageAdvice\022!.generate" +
      "dprotos.WaterUsageAdvice\032!.generatedprot" +
      "os.WaterUsageAdvice\022p\n\034UpdateElectricity" +
      "UsageAdvice\022\'.generatedprotos.Electricit" +
      "yUsageAdvice\032\'.generatedprotos.Electrici" +
      "tyUsageAdvice\022E\n\026DeleteWaterUsageAdvice\022" +
      "\023.generatedprotos.ID\032\026.generatedprotos.E" +
      "mpty\022K\n\034DeleteElectricityUsageAdvice\022\023.g" +
      "eneratedprotos.ID\032\026.generatedprotos.Empt" +
      "y\022Q\n\027GetWaterUsageAdviceById\022\023.generated" +
      "protos.ID\032!.generatedprotos.WaterUsageAd" +
      "vice\022]\n\035GetElectricityUsageAdviceById\022\023." +
      "generatedprotos.ID\032\'.generatedprotos.Ele" +
      "ctricityUsageAdvice\022U\n\027GetWaterAdvicesBy" +
      "UserId\022\023.generatedprotos.ID\032%.generatedp" +
      "rotos.ListWaterUsageAdvice\022a\n\035GetElectri" +
      "cityAdvicesByUserId\022\023.generatedprotos.ID" +
      "\032+.generatedprotos.ListElectricityUsageA" +
      "dvice\022f\n\034AssignWaterUsageAdviceToUser\022\037." +
      "generatedprotos.AdviceCreation\032%.generat" +
      "edprotos.ListWaterUsageAdvice\022r\n\"AssignE" +
      "lectricityUsageAdviceToUser\022\037.generatedp" +
      "rotos.AdviceCreation\032+.generatedprotos.L" +
      "istElectricityUsageAdviceB\027\n\023via.generat" +
      "edprotosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_generatedprotos_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_generatedprotos_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generatedprotos_User_descriptor,
        new java.lang.String[] { "Id", "Username", "Password", "Role", "Area", });
    internal_static_generatedprotos_ListUsers_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_generatedprotos_ListUsers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generatedprotos_ListUsers_descriptor,
        new java.lang.String[] { "Users", });
    internal_static_generatedprotos_WaterUsage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_generatedprotos_WaterUsage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generatedprotos_WaterUsage_descriptor,
        new java.lang.String[] { "Id", "Amount", "Month", "Year", "UserId", });
    internal_static_generatedprotos_ElectricityUsage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_generatedprotos_ElectricityUsage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generatedprotos_ElectricityUsage_descriptor,
        new java.lang.String[] { "Id", "Amount", "Month", "Year", "UserId", });
    internal_static_generatedprotos_WaterUsageAdvice_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_generatedprotos_WaterUsageAdvice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generatedprotos_WaterUsageAdvice_descriptor,
        new java.lang.String[] { "Id", "Body", });
    internal_static_generatedprotos_ElectricityUsageAdvice_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_generatedprotos_ElectricityUsageAdvice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generatedprotos_ElectricityUsageAdvice_descriptor,
        new java.lang.String[] { "Id", "Body", });
    internal_static_generatedprotos_ID_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_generatedprotos_ID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generatedprotos_ID_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_generatedprotos_Empty_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_generatedprotos_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generatedprotos_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_generatedprotos_ListWaterUsage_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_generatedprotos_ListWaterUsage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generatedprotos_ListWaterUsage_descriptor,
        new java.lang.String[] { "Water", });
    internal_static_generatedprotos_ListElectricityUsage_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_generatedprotos_ListElectricityUsage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generatedprotos_ListElectricityUsage_descriptor,
        new java.lang.String[] { "Electricity", });
    internal_static_generatedprotos_ListWaterUsageAdvice_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_generatedprotos_ListWaterUsageAdvice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generatedprotos_ListWaterUsageAdvice_descriptor,
        new java.lang.String[] { "Water", });
    internal_static_generatedprotos_ListElectricityUsageAdvice_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_generatedprotos_ListElectricityUsageAdvice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generatedprotos_ListElectricityUsageAdvice_descriptor,
        new java.lang.String[] { "Electricity", });
    internal_static_generatedprotos_AdviceCreation_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_generatedprotos_AdviceCreation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generatedprotos_AdviceCreation_descriptor,
        new java.lang.String[] { "UserId", "AdviceId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
