// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package via.generatedprotos;

public interface ElectricityUsageAdviceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:generatedprotos.ElectricityUsageAdvice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string body = 2;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 2;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
