// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package via.generatedprotos;

public interface ListElectricityUsageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:generatedprotos.ListElectricityUsage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
   */
  java.util.List<via.generatedprotos.ElectricityUsage> 
      getElectricityList();
  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
   */
  via.generatedprotos.ElectricityUsage getElectricity(int index);
  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
   */
  int getElectricityCount();
  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
   */
  java.util.List<? extends via.generatedprotos.ElectricityUsageOrBuilder> 
      getElectricityOrBuilderList();
  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
   */
  via.generatedprotos.ElectricityUsageOrBuilder getElectricityOrBuilder(
      int index);
}
