// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package via.generatedprotos;

public interface ListUsageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:generatedprotos.ListUsage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  java.util.List<via.generatedprotos.WaterUsage> 
      getWaterList();
  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  via.generatedprotos.WaterUsage getWater(int index);
  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  int getWaterCount();
  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  java.util.List<? extends via.generatedprotos.WaterUsageOrBuilder> 
      getWaterOrBuilderList();
  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  via.generatedprotos.WaterUsageOrBuilder getWaterOrBuilder(
      int index);

  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 2;</code>
   */
  java.util.List<via.generatedprotos.ElectricityUsage> 
      getElectricityList();
  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 2;</code>
   */
  via.generatedprotos.ElectricityUsage getElectricity(int index);
  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 2;</code>
   */
  int getElectricityCount();
  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 2;</code>
   */
  java.util.List<? extends via.generatedprotos.ElectricityUsageOrBuilder> 
      getElectricityOrBuilderList();
  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 2;</code>
   */
  via.generatedprotos.ElectricityUsageOrBuilder getElectricityOrBuilder(
      int index);
}
