// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package via.generatedprotos;

public interface ListWaterUsageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:generatedprotos.ListWaterUsage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  java.util.List<via.generatedprotos.WaterUsage> 
      getWaterList();
  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  via.generatedprotos.WaterUsage getWater(int index);
  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  int getWaterCount();
  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  java.util.List<? extends via.generatedprotos.WaterUsageOrBuilder> 
      getWaterOrBuilderList();
  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  via.generatedprotos.WaterUsageOrBuilder getWaterOrBuilder(
      int index);
}
