// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package via.generatedprotos;

public interface WaterUsageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:generatedprotos.WaterUsage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>double amount = 2;</code>
   * @return The amount.
   */
  double getAmount();

  /**
   * <code>int32 month = 3;</code>
   * @return The month.
   */
  int getMonth();

  /**
   * <code>int32 year = 4;</code>
   * @return The year.
   */
  int getYear();

  /**
   * <code>int32 userId = 5;</code>
   * @return The userId.
   */
  int getUserId();
}
