// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package via.generatedprotos;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:generatedprotos.Empty)
    com.google.protobuf.MessageOrBuilder {
}
