// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package via.generatedprotos;

public interface ListElectricityUsageAdviceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:generatedprotos.ListElectricityUsageAdvice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .generatedprotos.ElectricityUsageAdvice electricity = 1;</code>
   */
  java.util.List<via.generatedprotos.ElectricityUsageAdvice> 
      getElectricityList();
  /**
   * <code>repeated .generatedprotos.ElectricityUsageAdvice electricity = 1;</code>
   */
  via.generatedprotos.ElectricityUsageAdvice getElectricity(int index);
  /**
   * <code>repeated .generatedprotos.ElectricityUsageAdvice electricity = 1;</code>
   */
  int getElectricityCount();
  /**
   * <code>repeated .generatedprotos.ElectricityUsageAdvice electricity = 1;</code>
   */
  java.util.List<? extends via.generatedprotos.ElectricityUsageAdviceOrBuilder> 
      getElectricityOrBuilderList();
  /**
   * <code>repeated .generatedprotos.ElectricityUsageAdvice electricity = 1;</code>
   */
  via.generatedprotos.ElectricityUsageAdviceOrBuilder getElectricityOrBuilder(
      int index);
}
