// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package via.generatedprotos;

public interface ListUsersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:generatedprotos.ListUsers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .generatedprotos.User users = 1;</code>
   */
  java.util.List<via.generatedprotos.User> 
      getUsersList();
  /**
   * <code>repeated .generatedprotos.User users = 1;</code>
   */
  via.generatedprotos.User getUsers(int index);
  /**
   * <code>repeated .generatedprotos.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .generatedprotos.User users = 1;</code>
   */
  java.util.List<? extends via.generatedprotos.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .generatedprotos.User users = 1;</code>
   */
  via.generatedprotos.UserOrBuilder getUsersOrBuilder(
      int index);
}
