// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package via.generatedprotos;

/**
 * Protobuf type {@code generatedprotos.ListWaterUsage}
 */
public final class ListWaterUsage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:generatedprotos.ListWaterUsage)
    ListWaterUsageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListWaterUsage.newBuilder() to construct.
  private ListWaterUsage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListWaterUsage() {
    water_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListWaterUsage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListWaterUsage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              water_ = new java.util.ArrayList<via.generatedprotos.WaterUsage>();
              mutable_bitField0_ |= 0x00000001;
            }
            water_.add(
                input.readMessage(via.generatedprotos.WaterUsage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        water_ = java.util.Collections.unmodifiableList(water_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.generatedprotos.Definitions.internal_static_generatedprotos_ListWaterUsage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.generatedprotos.Definitions.internal_static_generatedprotos_ListWaterUsage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.generatedprotos.ListWaterUsage.class, via.generatedprotos.ListWaterUsage.Builder.class);
  }

  public static final int WATER_FIELD_NUMBER = 1;
  private java.util.List<via.generatedprotos.WaterUsage> water_;
  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.generatedprotos.WaterUsage> getWaterList() {
    return water_;
  }
  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.generatedprotos.WaterUsageOrBuilder> 
      getWaterOrBuilderList() {
    return water_;
  }
  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  @java.lang.Override
  public int getWaterCount() {
    return water_.size();
  }
  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  @java.lang.Override
  public via.generatedprotos.WaterUsage getWater(int index) {
    return water_.get(index);
  }
  /**
   * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
   */
  @java.lang.Override
  public via.generatedprotos.WaterUsageOrBuilder getWaterOrBuilder(
      int index) {
    return water_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < water_.size(); i++) {
      output.writeMessage(1, water_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < water_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, water_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.generatedprotos.ListWaterUsage)) {
      return super.equals(obj);
    }
    via.generatedprotos.ListWaterUsage other = (via.generatedprotos.ListWaterUsage) obj;

    if (!getWaterList()
        .equals(other.getWaterList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getWaterCount() > 0) {
      hash = (37 * hash) + WATER_FIELD_NUMBER;
      hash = (53 * hash) + getWaterList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.generatedprotos.ListWaterUsage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.generatedprotos.ListWaterUsage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.generatedprotos.ListWaterUsage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.generatedprotos.ListWaterUsage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.generatedprotos.ListWaterUsage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.generatedprotos.ListWaterUsage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.generatedprotos.ListWaterUsage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.generatedprotos.ListWaterUsage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.generatedprotos.ListWaterUsage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.generatedprotos.ListWaterUsage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.generatedprotos.ListWaterUsage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.generatedprotos.ListWaterUsage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.generatedprotos.ListWaterUsage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code generatedprotos.ListWaterUsage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:generatedprotos.ListWaterUsage)
      via.generatedprotos.ListWaterUsageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.generatedprotos.Definitions.internal_static_generatedprotos_ListWaterUsage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.generatedprotos.Definitions.internal_static_generatedprotos_ListWaterUsage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.generatedprotos.ListWaterUsage.class, via.generatedprotos.ListWaterUsage.Builder.class);
    }

    // Construct using via.generatedprotos.ListWaterUsage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getWaterFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (waterBuilder_ == null) {
        water_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        waterBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.generatedprotos.Definitions.internal_static_generatedprotos_ListWaterUsage_descriptor;
    }

    @java.lang.Override
    public via.generatedprotos.ListWaterUsage getDefaultInstanceForType() {
      return via.generatedprotos.ListWaterUsage.getDefaultInstance();
    }

    @java.lang.Override
    public via.generatedprotos.ListWaterUsage build() {
      via.generatedprotos.ListWaterUsage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.generatedprotos.ListWaterUsage buildPartial() {
      via.generatedprotos.ListWaterUsage result = new via.generatedprotos.ListWaterUsage(this);
      int from_bitField0_ = bitField0_;
      if (waterBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          water_ = java.util.Collections.unmodifiableList(water_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.water_ = water_;
      } else {
        result.water_ = waterBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.generatedprotos.ListWaterUsage) {
        return mergeFrom((via.generatedprotos.ListWaterUsage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.generatedprotos.ListWaterUsage other) {
      if (other == via.generatedprotos.ListWaterUsage.getDefaultInstance()) return this;
      if (waterBuilder_ == null) {
        if (!other.water_.isEmpty()) {
          if (water_.isEmpty()) {
            water_ = other.water_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWaterIsMutable();
            water_.addAll(other.water_);
          }
          onChanged();
        }
      } else {
        if (!other.water_.isEmpty()) {
          if (waterBuilder_.isEmpty()) {
            waterBuilder_.dispose();
            waterBuilder_ = null;
            water_ = other.water_;
            bitField0_ = (bitField0_ & ~0x00000001);
            waterBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getWaterFieldBuilder() : null;
          } else {
            waterBuilder_.addAllMessages(other.water_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.generatedprotos.ListWaterUsage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.generatedprotos.ListWaterUsage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.generatedprotos.WaterUsage> water_ =
      java.util.Collections.emptyList();
    private void ensureWaterIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        water_ = new java.util.ArrayList<via.generatedprotos.WaterUsage>(water_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.generatedprotos.WaterUsage, via.generatedprotos.WaterUsage.Builder, via.generatedprotos.WaterUsageOrBuilder> waterBuilder_;

    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public java.util.List<via.generatedprotos.WaterUsage> getWaterList() {
      if (waterBuilder_ == null) {
        return java.util.Collections.unmodifiableList(water_);
      } else {
        return waterBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public int getWaterCount() {
      if (waterBuilder_ == null) {
        return water_.size();
      } else {
        return waterBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public via.generatedprotos.WaterUsage getWater(int index) {
      if (waterBuilder_ == null) {
        return water_.get(index);
      } else {
        return waterBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public Builder setWater(
        int index, via.generatedprotos.WaterUsage value) {
      if (waterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWaterIsMutable();
        water_.set(index, value);
        onChanged();
      } else {
        waterBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public Builder setWater(
        int index, via.generatedprotos.WaterUsage.Builder builderForValue) {
      if (waterBuilder_ == null) {
        ensureWaterIsMutable();
        water_.set(index, builderForValue.build());
        onChanged();
      } else {
        waterBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public Builder addWater(via.generatedprotos.WaterUsage value) {
      if (waterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWaterIsMutable();
        water_.add(value);
        onChanged();
      } else {
        waterBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public Builder addWater(
        int index, via.generatedprotos.WaterUsage value) {
      if (waterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWaterIsMutable();
        water_.add(index, value);
        onChanged();
      } else {
        waterBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public Builder addWater(
        via.generatedprotos.WaterUsage.Builder builderForValue) {
      if (waterBuilder_ == null) {
        ensureWaterIsMutable();
        water_.add(builderForValue.build());
        onChanged();
      } else {
        waterBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public Builder addWater(
        int index, via.generatedprotos.WaterUsage.Builder builderForValue) {
      if (waterBuilder_ == null) {
        ensureWaterIsMutable();
        water_.add(index, builderForValue.build());
        onChanged();
      } else {
        waterBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public Builder addAllWater(
        java.lang.Iterable<? extends via.generatedprotos.WaterUsage> values) {
      if (waterBuilder_ == null) {
        ensureWaterIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, water_);
        onChanged();
      } else {
        waterBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public Builder clearWater() {
      if (waterBuilder_ == null) {
        water_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        waterBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public Builder removeWater(int index) {
      if (waterBuilder_ == null) {
        ensureWaterIsMutable();
        water_.remove(index);
        onChanged();
      } else {
        waterBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public via.generatedprotos.WaterUsage.Builder getWaterBuilder(
        int index) {
      return getWaterFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public via.generatedprotos.WaterUsageOrBuilder getWaterOrBuilder(
        int index) {
      if (waterBuilder_ == null) {
        return water_.get(index);  } else {
        return waterBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public java.util.List<? extends via.generatedprotos.WaterUsageOrBuilder> 
         getWaterOrBuilderList() {
      if (waterBuilder_ != null) {
        return waterBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(water_);
      }
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public via.generatedprotos.WaterUsage.Builder addWaterBuilder() {
      return getWaterFieldBuilder().addBuilder(
          via.generatedprotos.WaterUsage.getDefaultInstance());
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public via.generatedprotos.WaterUsage.Builder addWaterBuilder(
        int index) {
      return getWaterFieldBuilder().addBuilder(
          index, via.generatedprotos.WaterUsage.getDefaultInstance());
    }
    /**
     * <code>repeated .generatedprotos.WaterUsage water = 1;</code>
     */
    public java.util.List<via.generatedprotos.WaterUsage.Builder> 
         getWaterBuilderList() {
      return getWaterFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.generatedprotos.WaterUsage, via.generatedprotos.WaterUsage.Builder, via.generatedprotos.WaterUsageOrBuilder> 
        getWaterFieldBuilder() {
      if (waterBuilder_ == null) {
        waterBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.generatedprotos.WaterUsage, via.generatedprotos.WaterUsage.Builder, via.generatedprotos.WaterUsageOrBuilder>(
                water_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        water_ = null;
      }
      return waterBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:generatedprotos.ListWaterUsage)
  }

  // @@protoc_insertion_point(class_scope:generatedprotos.ListWaterUsage)
  private static final via.generatedprotos.ListWaterUsage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.generatedprotos.ListWaterUsage();
  }

  public static via.generatedprotos.ListWaterUsage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListWaterUsage>
      PARSER = new com.google.protobuf.AbstractParser<ListWaterUsage>() {
    @java.lang.Override
    public ListWaterUsage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListWaterUsage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListWaterUsage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListWaterUsage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.generatedprotos.ListWaterUsage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

