// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package via.generatedprotos;

public interface ListWaterUsageAdviceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:generatedprotos.ListWaterUsageAdvice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .generatedprotos.WaterUsageAdvice water = 1;</code>
   */
  java.util.List<via.generatedprotos.WaterUsageAdvice> 
      getWaterList();
  /**
   * <code>repeated .generatedprotos.WaterUsageAdvice water = 1;</code>
   */
  via.generatedprotos.WaterUsageAdvice getWater(int index);
  /**
   * <code>repeated .generatedprotos.WaterUsageAdvice water = 1;</code>
   */
  int getWaterCount();
  /**
   * <code>repeated .generatedprotos.WaterUsageAdvice water = 1;</code>
   */
  java.util.List<? extends via.generatedprotos.WaterUsageAdviceOrBuilder> 
      getWaterOrBuilderList();
  /**
   * <code>repeated .generatedprotos.WaterUsageAdvice water = 1;</code>
   */
  via.generatedprotos.WaterUsageAdviceOrBuilder getWaterOrBuilder(
      int index);
}
