// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package via.generatedprotos;

/**
 * Protobuf type {@code generatedprotos.ListElectricityUsage}
 */
public final class ListElectricityUsage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:generatedprotos.ListElectricityUsage)
    ListElectricityUsageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListElectricityUsage.newBuilder() to construct.
  private ListElectricityUsage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListElectricityUsage() {
    electricity_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListElectricityUsage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListElectricityUsage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              electricity_ = new java.util.ArrayList<via.generatedprotos.ElectricityUsage>();
              mutable_bitField0_ |= 0x00000001;
            }
            electricity_.add(
                input.readMessage(via.generatedprotos.ElectricityUsage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        electricity_ = java.util.Collections.unmodifiableList(electricity_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.generatedprotos.Definitions.internal_static_generatedprotos_ListElectricityUsage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.generatedprotos.Definitions.internal_static_generatedprotos_ListElectricityUsage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.generatedprotos.ListElectricityUsage.class, via.generatedprotos.ListElectricityUsage.Builder.class);
  }

  public static final int ELECTRICITY_FIELD_NUMBER = 1;
  private java.util.List<via.generatedprotos.ElectricityUsage> electricity_;
  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.generatedprotos.ElectricityUsage> getElectricityList() {
    return electricity_;
  }
  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.generatedprotos.ElectricityUsageOrBuilder> 
      getElectricityOrBuilderList() {
    return electricity_;
  }
  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
   */
  @java.lang.Override
  public int getElectricityCount() {
    return electricity_.size();
  }
  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
   */
  @java.lang.Override
  public via.generatedprotos.ElectricityUsage getElectricity(int index) {
    return electricity_.get(index);
  }
  /**
   * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
   */
  @java.lang.Override
  public via.generatedprotos.ElectricityUsageOrBuilder getElectricityOrBuilder(
      int index) {
    return electricity_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < electricity_.size(); i++) {
      output.writeMessage(1, electricity_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < electricity_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, electricity_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.generatedprotos.ListElectricityUsage)) {
      return super.equals(obj);
    }
    via.generatedprotos.ListElectricityUsage other = (via.generatedprotos.ListElectricityUsage) obj;

    if (!getElectricityList()
        .equals(other.getElectricityList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getElectricityCount() > 0) {
      hash = (37 * hash) + ELECTRICITY_FIELD_NUMBER;
      hash = (53 * hash) + getElectricityList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.generatedprotos.ListElectricityUsage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.generatedprotos.ListElectricityUsage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.generatedprotos.ListElectricityUsage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.generatedprotos.ListElectricityUsage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.generatedprotos.ListElectricityUsage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.generatedprotos.ListElectricityUsage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.generatedprotos.ListElectricityUsage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.generatedprotos.ListElectricityUsage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.generatedprotos.ListElectricityUsage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.generatedprotos.ListElectricityUsage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.generatedprotos.ListElectricityUsage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.generatedprotos.ListElectricityUsage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.generatedprotos.ListElectricityUsage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code generatedprotos.ListElectricityUsage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:generatedprotos.ListElectricityUsage)
      via.generatedprotos.ListElectricityUsageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.generatedprotos.Definitions.internal_static_generatedprotos_ListElectricityUsage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.generatedprotos.Definitions.internal_static_generatedprotos_ListElectricityUsage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.generatedprotos.ListElectricityUsage.class, via.generatedprotos.ListElectricityUsage.Builder.class);
    }

    // Construct using via.generatedprotos.ListElectricityUsage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getElectricityFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (electricityBuilder_ == null) {
        electricity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        electricityBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.generatedprotos.Definitions.internal_static_generatedprotos_ListElectricityUsage_descriptor;
    }

    @java.lang.Override
    public via.generatedprotos.ListElectricityUsage getDefaultInstanceForType() {
      return via.generatedprotos.ListElectricityUsage.getDefaultInstance();
    }

    @java.lang.Override
    public via.generatedprotos.ListElectricityUsage build() {
      via.generatedprotos.ListElectricityUsage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.generatedprotos.ListElectricityUsage buildPartial() {
      via.generatedprotos.ListElectricityUsage result = new via.generatedprotos.ListElectricityUsage(this);
      int from_bitField0_ = bitField0_;
      if (electricityBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          electricity_ = java.util.Collections.unmodifiableList(electricity_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.electricity_ = electricity_;
      } else {
        result.electricity_ = electricityBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.generatedprotos.ListElectricityUsage) {
        return mergeFrom((via.generatedprotos.ListElectricityUsage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.generatedprotos.ListElectricityUsage other) {
      if (other == via.generatedprotos.ListElectricityUsage.getDefaultInstance()) return this;
      if (electricityBuilder_ == null) {
        if (!other.electricity_.isEmpty()) {
          if (electricity_.isEmpty()) {
            electricity_ = other.electricity_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureElectricityIsMutable();
            electricity_.addAll(other.electricity_);
          }
          onChanged();
        }
      } else {
        if (!other.electricity_.isEmpty()) {
          if (electricityBuilder_.isEmpty()) {
            electricityBuilder_.dispose();
            electricityBuilder_ = null;
            electricity_ = other.electricity_;
            bitField0_ = (bitField0_ & ~0x00000001);
            electricityBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getElectricityFieldBuilder() : null;
          } else {
            electricityBuilder_.addAllMessages(other.electricity_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.generatedprotos.ListElectricityUsage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.generatedprotos.ListElectricityUsage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.generatedprotos.ElectricityUsage> electricity_ =
      java.util.Collections.emptyList();
    private void ensureElectricityIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        electricity_ = new java.util.ArrayList<via.generatedprotos.ElectricityUsage>(electricity_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.generatedprotos.ElectricityUsage, via.generatedprotos.ElectricityUsage.Builder, via.generatedprotos.ElectricityUsageOrBuilder> electricityBuilder_;

    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public java.util.List<via.generatedprotos.ElectricityUsage> getElectricityList() {
      if (electricityBuilder_ == null) {
        return java.util.Collections.unmodifiableList(electricity_);
      } else {
        return electricityBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public int getElectricityCount() {
      if (electricityBuilder_ == null) {
        return electricity_.size();
      } else {
        return electricityBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public via.generatedprotos.ElectricityUsage getElectricity(int index) {
      if (electricityBuilder_ == null) {
        return electricity_.get(index);
      } else {
        return electricityBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public Builder setElectricity(
        int index, via.generatedprotos.ElectricityUsage value) {
      if (electricityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElectricityIsMutable();
        electricity_.set(index, value);
        onChanged();
      } else {
        electricityBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public Builder setElectricity(
        int index, via.generatedprotos.ElectricityUsage.Builder builderForValue) {
      if (electricityBuilder_ == null) {
        ensureElectricityIsMutable();
        electricity_.set(index, builderForValue.build());
        onChanged();
      } else {
        electricityBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public Builder addElectricity(via.generatedprotos.ElectricityUsage value) {
      if (electricityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElectricityIsMutable();
        electricity_.add(value);
        onChanged();
      } else {
        electricityBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public Builder addElectricity(
        int index, via.generatedprotos.ElectricityUsage value) {
      if (electricityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElectricityIsMutable();
        electricity_.add(index, value);
        onChanged();
      } else {
        electricityBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public Builder addElectricity(
        via.generatedprotos.ElectricityUsage.Builder builderForValue) {
      if (electricityBuilder_ == null) {
        ensureElectricityIsMutable();
        electricity_.add(builderForValue.build());
        onChanged();
      } else {
        electricityBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public Builder addElectricity(
        int index, via.generatedprotos.ElectricityUsage.Builder builderForValue) {
      if (electricityBuilder_ == null) {
        ensureElectricityIsMutable();
        electricity_.add(index, builderForValue.build());
        onChanged();
      } else {
        electricityBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public Builder addAllElectricity(
        java.lang.Iterable<? extends via.generatedprotos.ElectricityUsage> values) {
      if (electricityBuilder_ == null) {
        ensureElectricityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, electricity_);
        onChanged();
      } else {
        electricityBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public Builder clearElectricity() {
      if (electricityBuilder_ == null) {
        electricity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        electricityBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public Builder removeElectricity(int index) {
      if (electricityBuilder_ == null) {
        ensureElectricityIsMutable();
        electricity_.remove(index);
        onChanged();
      } else {
        electricityBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public via.generatedprotos.ElectricityUsage.Builder getElectricityBuilder(
        int index) {
      return getElectricityFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public via.generatedprotos.ElectricityUsageOrBuilder getElectricityOrBuilder(
        int index) {
      if (electricityBuilder_ == null) {
        return electricity_.get(index);  } else {
        return electricityBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public java.util.List<? extends via.generatedprotos.ElectricityUsageOrBuilder> 
         getElectricityOrBuilderList() {
      if (electricityBuilder_ != null) {
        return electricityBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(electricity_);
      }
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public via.generatedprotos.ElectricityUsage.Builder addElectricityBuilder() {
      return getElectricityFieldBuilder().addBuilder(
          via.generatedprotos.ElectricityUsage.getDefaultInstance());
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public via.generatedprotos.ElectricityUsage.Builder addElectricityBuilder(
        int index) {
      return getElectricityFieldBuilder().addBuilder(
          index, via.generatedprotos.ElectricityUsage.getDefaultInstance());
    }
    /**
     * <code>repeated .generatedprotos.ElectricityUsage electricity = 1;</code>
     */
    public java.util.List<via.generatedprotos.ElectricityUsage.Builder> 
         getElectricityBuilderList() {
      return getElectricityFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.generatedprotos.ElectricityUsage, via.generatedprotos.ElectricityUsage.Builder, via.generatedprotos.ElectricityUsageOrBuilder> 
        getElectricityFieldBuilder() {
      if (electricityBuilder_ == null) {
        electricityBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.generatedprotos.ElectricityUsage, via.generatedprotos.ElectricityUsage.Builder, via.generatedprotos.ElectricityUsageOrBuilder>(
                electricity_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        electricity_ = null;
      }
      return electricityBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:generatedprotos.ListElectricityUsage)
  }

  // @@protoc_insertion_point(class_scope:generatedprotos.ListElectricityUsage)
  private static final via.generatedprotos.ListElectricityUsage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.generatedprotos.ListElectricityUsage();
  }

  public static via.generatedprotos.ListElectricityUsage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListElectricityUsage>
      PARSER = new com.google.protobuf.AbstractParser<ListElectricityUsage>() {
    @java.lang.Override
    public ListElectricityUsage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListElectricityUsage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListElectricityUsage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListElectricityUsage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.generatedprotos.ListElectricityUsage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

