// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

public final class Definitions {
  private Definitions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WaterUsage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WaterUsage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ElectricityUsage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ElectricityUsage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WaterUsageAdvice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WaterUsageAdvice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ElectricityUsageAdvice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ElectricityUsageAdvice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListUsage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListUsage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021definitions.proto\"D\n\004User\022\n\n\002id\030\001 \001(\005\022" +
      "\020\n\010username\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\014\n\004r" +
      "ole\030\004 \001(\005\"U\n\nWaterUsage\022\n\n\002id\030\001 \001(\005\022\016\n\006a" +
      "mount\030\002 \001(\001\022\r\n\005month\030\003 \001(\005\022\014\n\004year\030\004 \001(\005" +
      "\022\016\n\006userId\030\005 \001(\005\"[\n\020ElectricityUsage\022\n\n\002" +
      "id\030\001 \001(\005\022\016\n\006amount\030\002 \001(\001\022\r\n\005month\030\003 \001(\005\022" +
      "\014\n\004year\030\004 \001(\005\022\016\n\006userId\030\005 \001(\005\",\n\020WaterUs" +
      "ageAdvice\022\n\n\002id\030\001 \001(\005\022\014\n\004body\030\002 \001(\t\"2\n\026E" +
      "lectricityUsageAdvice\022\n\n\002id\030\001 \001(\005\022\014\n\004bod" +
      "y\030\002 \001(\t\"\007\n\005Empty\"O\n\tListUsage\022\032\n\005water\030\001" +
      " \003(\0132\013.WaterUsage\022&\n\013electricity\030\002 \003(\0132\021" +
      ".ElectricityUsage2\216\001\n\024ResourcesConsumpti" +
      "on\0220\n\023LogElectricityUsage\022\021.ElectricityU" +
      "sage\032\006.Empty\022$\n\rLogWaterUsage\022\013.WaterUsa" +
      "ge\032\006.Empty\022\036\n\010GetUsage\022\006.Empty\032\n.ListUsa" +
      "geB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "Username", "Password", "Role", });
    internal_static_WaterUsage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WaterUsage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WaterUsage_descriptor,
        new java.lang.String[] { "Id", "Amount", "Month", "Year", "UserId", });
    internal_static_ElectricityUsage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ElectricityUsage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ElectricityUsage_descriptor,
        new java.lang.String[] { "Id", "Amount", "Month", "Year", "UserId", });
    internal_static_WaterUsageAdvice_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_WaterUsageAdvice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WaterUsageAdvice_descriptor,
        new java.lang.String[] { "Id", "Body", });
    internal_static_ElectricityUsageAdvice_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ElectricityUsageAdvice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ElectricityUsageAdvice_descriptor,
        new java.lang.String[] { "Id", "Body", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_ListUsage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ListUsage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListUsage_descriptor,
        new java.lang.String[] { "Water", "Electricity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
