// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

public interface ElectricityUsageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ElectricityUsage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>double amount = 2;</code>
   * @return The amount.
   */
  double getAmount();

  /**
   * <code>int32 month = 3;</code>
   * @return The month.
   */
  int getMonth();

  /**
   * <code>int32 year = 4;</code>
   * @return The year.
   */
  int getYear();
}
