// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
