// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

public interface ListUsageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListUsage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .WaterUsage water = 1;</code>
   */
  java.util.List<WaterUsage> 
      getWaterList();
  /**
   * <code>repeated .WaterUsage water = 1;</code>
   */
  WaterUsage getWater(int index);
  /**
   * <code>repeated .WaterUsage water = 1;</code>
   */
  int getWaterCount();
  /**
   * <code>repeated .WaterUsage water = 1;</code>
   */
  java.util.List<? extends WaterUsageOrBuilder> 
      getWaterOrBuilderList();
  /**
   * <code>repeated .WaterUsage water = 1;</code>
   */
  WaterUsageOrBuilder getWaterOrBuilder(
      int index);

  /**
   * <code>repeated .ElectricityUsage electricity = 2;</code>
   */
  java.util.List<ElectricityUsage> 
      getElectricityList();
  /**
   * <code>repeated .ElectricityUsage electricity = 2;</code>
   */
  ElectricityUsage getElectricity(int index);
  /**
   * <code>repeated .ElectricityUsage electricity = 2;</code>
   */
  int getElectricityCount();
  /**
   * <code>repeated .ElectricityUsage electricity = 2;</code>
   */
  java.util.List<? extends ElectricityUsageOrBuilder> 
      getElectricityOrBuilderList();
  /**
   * <code>repeated .ElectricityUsage electricity = 2;</code>
   */
  ElectricityUsageOrBuilder getElectricityOrBuilder(
      int index);
}
